pipeline {
    agent {
        dockerfile {
            dir '.devops'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Initialise') {
            steps {
                echo "Test"
                sh "docker -v"
                sh "npm -v"
            }
        }
    }
}